src/objects/LF_Contact__c.object
<CustomObject>
    <description>Contact of individual whose case is being opened concerning items Lost</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FName__c</fullName>
        <label>FName</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LName__c</fullName>
        <label>LName</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>LF_Contact</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>LF_Contact_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LF_Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LF_Location__c.object
<CustomObject>
    <fields>
        <fullName>LocName__c</fullName>
        <label>LocName</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>LF_Location</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>LF_Location_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LF_Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LF_Main__c.object
<CustomObject>
    <description>Main object for Lost &amp; Found system, stores key info and relationship to other tables</description>
    <fields>
        <fullName>Found_Comments__c</fullName>
        <label>Found_Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>General_Comments__c</fullName>
        <label>General_Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LF_Contact_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LF_Contact_ID</label>
        <referenceTo>LF_Contact__c</referenceTo>
        <relationshipLabel>LF_Mains_Contact</relationshipLabel>
        <relationshipName>LF_Mains_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LF_Location_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup from Main to Location</description>
        <label>LF_Location_ID</label>
        <referenceTo>LF_Location__c</referenceTo>
        <relationshipLabel>LF_Mains_Loc</relationshipLabel>
        <relationshipName>LF_Mains_Loc</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LostDate__c</fullName>
        <label>LostDate</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lost_Comments__c</fullName>
        <label>Lost_Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>LF_Main</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>LF_Main_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LF_Mains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LFHomeController.cls
public class LFHomeController {

    public List<MainObj> listOfRecords {set;}
    
    public List<MainObj> getlistOfRecords(){
        
        //Class for LFHome View
        List<MainObj> listOfRecords = new List<MainObj>();

        //Main Object
        List<LF_Main__c> results = new List<LF_Main__c>();
        
        //Get data from Objects
        results = [select id,name,Lost_Comments__c,General_Comments__c,Found_Comments__c,LostDate__c,
             LF_Location_ID__r.LocName__c,
             LF_Contact_ID__r.FName__c,
             LF_Contact_ID__r.LName__c,
             LF_Contact_ID__r.Email__c,
             LF_Contact_ID__r.Phone__c
             from LF_Main__c];
        
        //Populate custom object for LFHome view
        for(LF_Main__C obj : results){
				MainObj mObj = new MainObj();
            	mObj.ContactName = obj.LF_Contact_ID__r.FName__c + '.' + obj.LF_Contact_ID__r.LName__c;
            	mObj.LComments = obj.Lost_Comments__c;
            	mObj.GComments = (obj.General_Comments__c == null ? 'No General Comments Specified' :  obj.General_Comments__c) ;
            	mObj.LocName = obj.LF_Location_ID__r.LocName__c;

          listOfRecords.add(mObj);          
        }
            
        return listOfRecords;
   }
       
}