src/objects/LF_Contact__c.object
<CustomObject>
    <description>Contact of individual whose case is being opened concerning items Lost</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FName__c</fullName>
        <label>FName</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LName__c</fullName>
        <label>LName</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>LF_Contact</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>LF_Contact_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LF_Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LF_EntryType__c.object
<CustomObject>
    <description>Type of entry being recorded</description>
    <fields>
        <fullName>EntryName__c</fullName>
        <label>EntryName</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>LF_EntryType</label>
    <nameField>
        <label>LF_EntryType_ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LF_EntryTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LF_ItemMap__c.object
<CustomObject>
    <description>Junction object between LF_Main and LF_ItemType</description>
    <fields>
        <fullName>LF_ItemType_ID__c</fullName>
        <label>LF_ItemType_ID</label>
        <referenceTo>LF_ItemType__c</referenceTo>
        <relationshipLabel>LF_ItemMaps</relationshipLabel>
        <relationshipName>LF_ItemMaps</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LF_Main_ID__c</fullName>
        <label>LF_Main_ID</label>
        <referenceTo>LF_Main__c</referenceTo>
        <relationshipLabel>LF_ItemMaps</relationshipLabel>
        <relationshipName>LF_ItemMaps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>LF_ItemMap</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>LF_ItemMap_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LF_ItemMaps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LF_ItemType__c.object
<CustomObject>
    <description>What kind of item is lost or found. for ex: Wallet, Keys, Pen, Jacket</description>
    <fields>
        <fullName>ItemTypeName__c</fullName>
        <label>ItemTypeName</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>LF_ItemType</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>LF_ItemType_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LF_ItemTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LF_Location__c.object
<CustomObject>
    <fields>
        <fullName>LocName__c</fullName>
        <label>LocName</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>LF_Location</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>LF_Location_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LF_Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LF_Main__c.object
<CustomObject>
    <description>Main object for Lost &amp; Found system, stores key info and relationship to other tables</description>
    <fields>
        <fullName>Found_Comments__c</fullName>
        <label>Found_Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>General_Comments__c</fullName>
        <label>General_Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LF_Contact_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LF_Contact_ID</label>
        <referenceTo>LF_Contact__c</referenceTo>
        <relationshipLabel>LF_Mains_Contact</relationshipLabel>
        <relationshipName>LF_Mains_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LF_EntryType_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LF_EntryType_ID</label>
        <referenceTo>LF_EntryType__c</referenceTo>
        <relationshipLabel>LF_Mains_EType</relationshipLabel>
        <relationshipName>LF_Mains_EType</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LF_Location_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup from Main to Location</description>
        <label>LF_Location_ID</label>
        <referenceTo>LF_Location__c</referenceTo>
        <relationshipLabel>LF_Mains_Loc</relationshipLabel>
        <relationshipName>LF_Mains_Loc</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LostDate__c</fullName>
        <label>LostDate</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lost_Comments__c</fullName>
        <label>Lost_Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>LF_Main</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>LF_Main_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LF_Mains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MainController.cls
public with sharing class MainController {

    public MainController() {
        rptDate = System.Date.today();
    }

    public Date rptDate {get;set;}
    
    public String lComm{set; get;}
    public String gComm {get; set;}
    public string FName {get; set;}
    public string LName {get; set;}
    public string Email {get; set;}
    public string Phone{get; set;}
    public List<Id> selITypes {set; get;}
	public Id selLocId {set;get;}
    public Id selEntry {set;get;}
    
    public List<SelectOption> getItemTypes(){
        List<LF_ItemType__c> s = [Select Id,ItemTypeName__c from LF_ItemType__c];
        List<SelectOption> o = new List<SelectOption>();
        
        for(LF_ItemType__c l : s)
            o.add(new SelectOption(l.Id,l.ItemTypeName__c));
        
        return o;
    }
    public List<SelectOption> getLOrFOptions(){
        List<LF_EntryType__c> e = [select EntryName__c from LF_EntryType__c];
        
        List<SelectOption> s = new List<SelectOption>();
        for(LF_EntryType__c eT : e){
            s.add(new SelectOption(eT.Id,eT.EntryName__c));
        }
        
        return s;
    }
    
    public List<SelectOption> getLocs(){
        List<LF_Location__c> locs = [Select Id,LocName__c from LF_Location__c];
        List<SelectOption> lo = new List<SelectOption>();
        
        for(LF_Location__c loc : locs){
            lo.add(new SelectOption(loc.Id,loc.LocName__c));
        }
        return lo;
    }
    
   
    
    //Save
    public PageReference SaveLF(){
        
        //Insert Contact info
        try
        {
            LF_Contact__c c = new LF_Contact__c();
            c.Email__c = this.Email;
            c.Phone__c = this.Phone;
            c.FName__c = this.FName;
            c.LName__c = this.LName;
            upsert c;
            
            
            //Insert Main Object
            LF_Main__c m = new LF_Main__c();
            m.Lost_Comments__c = this.lComm;
            m.General_Comments__c = this.gComm;
            m.Found_Comments__c = this.lComm;
            m.LF_Location_ID__c = this.selLocId;
            m.LF_Contact_ID__c = c.Id;
            m.LostDate__c = this.rptDate;
            m.LF_EntryType_ID__c = this.selEntry;
            
            upsert m;
            
            //Insert in ItemMaps (Junction)
            List<LF_ItemMap__c> toInsert = new List<LF_ItemMap__c>();
            for(String selId: selITypes){
                LF_ItemMap__c i = new LF_ItemMap__c();
                i.LF_Main_ID__c = m.Id;
                i.LF_ItemType_ID__c = selId;
                toInsert.add(i);
            }
            
            upsert toInsert;
            
            PageReference homePage = Page.LFHome;
            homePage.setRedirect(true);
            return homePage;
        }
        Catch(DmlException d)
        {
            System.debug(d.getMessage());
            return null;
        }
    }
}